Add Swift 5.2 support
SwiftGen/StencilSwiftKit pull request #125
Opened 2020-05-20 08:57 UTC by reversepanda

Change Log

- Fix a crash due to order of conditions
- Change dependency of the Stencil package to the master branch; this is not optimal, but Stencil didn't have a release for a long time and Swift 5.2. support is only available on the master branch
- Adapt code to Swift 5.2/Stencil master (API changes)

2020-05-21 14:15 UTC, djbe requested changes
As mentioned in comments, It's a bad idea to depend on master, I'll see about making a Stencil release. Missing from this PR is an update to the podspec/Podfile.

2020-05-21 14:15 UTC, djbe commented on Sources/StencilSwiftKit/Filters+Strings.swift
> +    if idx < scalars.endIndex, idx > scalars.index(after: start),
I'm assuming this fixes the crash?

2020-05-21 14:15 UTC, djbe commented on Tests/StencilSwiftKitTests/CallNodeTests.swift
> +    let context = Context(dictionary: ["": ""])
Why is this needed? (same for the lines below)

2020-05-21 14:15 UTC, djbe commented on Package.swift
> +      .package(url: "https://github.com/stencilproject/Stencil.git", .branch("master"))
I'd rather avoid this if possible, I can probably push through a Stencil release if needed.

Do we have Swift 5 support in Stencil yet? (it's been a while)

2020-05-21 14:15 UTC, djbe commented on .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
> +<?xml version="1.0" encoding="UTF-8"?>
Pretty sure we should add this folder to gitignore.

2020-08-29 11:00 UTC, AliSoftware commented
PR #127 is pending and will soon update StencilSwiftKit to latest version of Stencil. This means we can stop pointing to the master branch in this PR, and that the changes like [this one](https://github.com/SwiftGen/StencilSwiftKit/pull/125#discussion_r428676384) will already be that other PR.

2020-10-09 13:03 UTC, djbe commented
Thank you for your contribution.

I know it's been a while, and in the mean time, this has been superseded by #127, which (amongst other things) adds support for Swift 5.

2020-10-09 13:03 UTC, closed without merging